[display]
show_time = false
# greeting = "Welcome to the system!"
# align_greeting = "center"
issue = false

[layout]
width = 60
window_padding = 2
container_padding = 1
prompt_padding = 1

[layout.widgets]
time_position = "top"
status_position = "bottom"

[remember]
username = true
session = false
user_session = true

[user_menu]
enabled = true
min_uid = 1000
max_uid = 60000

[secret]
mode = "characters"
characters = "*"

[keybindings]
command = 2
sessions = 3
background = 4
power = 12

[background]
kind = "fog"
fps = 30

[brand]
path = "/etc/tuigreet/brand.txt"
align = "center"

[background.fog]
speed = 1.0
scale = 1.0
dim = "cyan"
bright = "cyan"

[session]
sessions_dirs = ["/usr/share/wayland-sessions", "/usr/share/xsessions"]
xsessions_dirs = []
environments = []

[power]
use_setsid = false

[theme]
# foreground = text/icon color, .bg = background color
border = "white"
text = "green"
time = "blue"
container = "black"
title = "cyan"
greet = "yellow"
brand = "light-green"
prompt = "white"
action = "light-gray"
button = "gray"
