# lib/stage-greetd.sh — write /etc/greetd/config.toml and the
# /usr/local/bin/start-hyprland launcher.
#
# Two greeter backends supported:
#   tuigreet      — the existing tty greeter (built in stage-configs)
#   dms-greeter   — vendored in stage-vendor; uses Wayland directly
#
# Both backends exec the same Hyprland launcher, which sets the env and
# execs Hyprland.

stage_greetd() {
  require_root
  section "greetd: wiring ${NOKRON_GREETER_BACKEND}"

  # 1. Write the Hyprland launcher. greetd's `command` runs as the greeter
  #    user, but the actual session starts as the desktop user via
  #    tuigreet's --cmd or dms-greeter's user menu.
  install -d /usr/local/bin
  install_start_hyprland

  # 2. Configure greetd.
  local cfg="/etc/greetd/config.toml"
  install -d /etc/greetd

  if [[ -f "${cfg}" ]]; then
    local bak="${cfg}.bak.$(date +%Y%m%d-%H%M%S)"
    info "backing up ${cfg} → ${bak}"
    cp -p "${cfg}" "${bak}"
  fi

  local tmp; tmp="$(mktemp /etc/greetd/config.toml.XXXXXX)"
  case "${NOKRON_GREETER_BACKEND}" in
    tuigreet)
      cat > "${tmp}" <<'GREETD_EOF'
[terminal]
vt = 1

[default_session]
# We don't add env exports here on purpose — Hyprland's startup.lua applies
# them to its child processes (dms shell, kitty, etc.) before exec-once
# fires `dms run`. Inlining them in the greetd command would require
# extra wrappers and complicate `start-hyprland` resolution.
#
# `command` chains `||` to /usr/bin/start-hyprland (Hyprland RPM wrapper,
# always present) so even if our /usr/local/bin/start-hyprland env-exports
# launcher failed to install, login still works (just without env exports
# — dms may need a manual relaunch in that case).
command = "sh -c '. /etc/tuigreet/palette.sh; exec tuigreet --cmd /usr/local/bin/start-hyprland || exec tuigreet --cmd /usr/bin/start-hyprland'"
# Use `greeter` user (uid 981, /usr/bin/nologin shell is fine — exec_cmd
# bypasses the login shell). The dms-greeter user creation pattern uses
# `greeter`; the greetd RPM's `greetd` user has /usr/sbin/nologin and
# is reserved for the daemon itself, not sessions.
user = "greeter"
GREETD_EOF
      ;;
    dms-greeter)
      cat > "${tmp}" <<'GREETD_EOF'
[terminal]
vt = 1

[default_session]
command = "dms-greeter --command /usr/local/bin/start-hyprland || dms-greeter --command /usr/bin/start-hyprland"
user = "greeter"
GREETD_EOF
      ;;
    *)
      die "unknown greeter backend: ${NOKRON_GREETER_BACKEND}"
      ;;
  esac

  install -m 0644 "${tmp}" "${cfg}"

  info "wrote ${cfg}"
}

install_start_hyprland() {
  local dst=/usr/local/bin/start-hyprland
  local session="${NOKRON_GREETER_SESSION}"

  # Hyprland needs a few env vars before exec. The launcher script sets
  # them and then execs whatever session the greeter handed us (default:
  # Hyprland; override via NOKRON_SESSION env if a user logs into something
  # else).
  cat > "${dst}" <<EOF
#!/bin/sh
# start-hyprland — greetd session launcher for Hyprland.
# Generated by nokron/fedora_install.sh.

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=Hyprland
export QT_QPA_PLATFORM=wayland
export MOZ_ENABLE_WAYLAND=1
export _JAVA_AWT_WM_NONREPARENTING=1
export GBM_BACKEND=\${GBM_BACKEND:-nvidia-drm,\${GBM_BACKEND:-}}

# Drop the systemd-managed user session env if present.
if [ -f "\${XDG_RUNTIME_DIR:-/run/user/\$(id -u)}/dbus.session" ]; then
  . "\${XDG_RUNTIME_DIR}/dbus.session"
fi

exec ${session}
EOF

  chmod 0755 "${dst}"
  info "wrote ${dst}"
}
