-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

hl.config({
	input = {
		-- empty inherits XKB_DEFAULT_LAYOUT (libxkbcommon), falls back to "us"
		kb_layout = "",
		numlock_by_default = true,
		follow_mouse = 0,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

-- Snappy animations. Use linear/quick curves (fast ramp, no long easing tail)
-- and high speeds. appleEaseInOut's symmetric shape felt slow even at 20x;
-- linear with high speed feels instant while still having a visible transition.
hl.curve("appleEaseInOut",  { type = "bezier", points = { {0.42, 0.0}, {0.58, 1.0} } })
hl.curve("appleEaseOut",    { type = "bezier", points = { {0.16, 1.0}, {0.3,  1.0} } })
hl.curve("quick",           { type = "bezier", points = { {0.15, 0.0}, {0.1,  1.0} } })
hl.curve("almostLinear",    { type = "bezier", points = { {0.5,  0.5}, {0.75, 1.0} } })

hl.animation({ leaf = "global",       enabled = true,  speed = 1.8,  bezier = "linear" })
hl.animation({ leaf = "border",       enabled = true,  speed = 1.5,  bezier = "linear" })
hl.animation({ leaf = "windowsIn",    enabled = true,  speed = 2.5,  bezier = "quick",      style = "popin 87%" })
hl.animation({ leaf = "windowsOut",   enabled = false, bezier = "appleEaseOut", style = "popin 95%" })
hl.animation({ leaf = "windowsMove",  enabled = false, bezier = "appleEaseOut" })
hl.animation({ leaf = "fadeIn",       enabled = false, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",      enabled = false, bezier = "almostLinear" })
hl.animation({ leaf = "fade",         enabled = true,  speed = 1.5,  bezier = "linear" })
hl.animation({ leaf = "workspaces",   enabled = true,  speed = 2.0,  bezier = "linear",     style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true,  speed = 2.0,  bezier = "linear",     style = "fade" })
hl.animation({ leaf = "workspacesOut",enabled = true,  speed = 2.0,  bezier = "linear",     style = "fade" })
hl.animation({ leaf = "zoomFactor",   enabled = true,  speed = 1.0,  bezier = "linear" })
hl.animation({ leaf = "layers",       enabled = true,  speed = 1.5,  bezier = "quick" })
hl.animation({ leaf = "layersIn",     enabled = true,  speed = 1.5,  bezier = "quick",      style = "fade" })
hl.animation({ leaf = "layersOut",    enabled = true,  speed = 1.5,  bezier = "linear",     style = "fade" })

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, tile = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
